'''Veer Khosla
CS151 A
Lab 7
lsystem23.py'''

#Version 1

import sys


def init():
    '''returns empty L-system'''
    lsys = ['', []]
    return lsys


def setBase(lsys, base):
    '''sets the value of the base of L-system'''
    lsys[0] = base
    

def getBase(lsys):
    '''returns the base of L-system'''
    return lsys[0]
    

def addRule(lsys, rule):
    '''adds a rule to L-system'''
    lsys[1].append(rule)


def getRule(lsys, ruleIdx):
    '''returns a rule to L-system'''
    return lsys[1][ruleIdx]


def createLsystemFromFile(filename):
    """ Create an L-system list by reading in the specified file """
    lsys = init()          
    fp = open(filename, "r")
    lines = fp.readlines()
    fp.close()

    for line in lines:
        line = line.strip()
        words = line.split(' ')
        if words[0] == 'base':
            setBase(lsys, words[1])
        else:
            if words[0] == 'rule':
                addRule(lsys, (words[1], words[2]))
    return lsys
					

def buildString( lsys, n ):
    """ Return a string generated by applying the L-system rules  
        n times"""
    nstring = getBase(lsys) 
    rule = getRule(lsys, 0)
    symbol = rule[0]
    replacement = rule[1]
    for i in range(n):
        nstring = nstring.replace(symbol, replacement)
    return nstring


def main(argv):
    if len(argv) < 3:
        print("Usage : python3 lsystem.py <in_filename> <num_iterations>")
        exit()

    lsys_filename = argv[1]
    lsys = createLsystemFromFile( lsys_filename )
    print(lsys)
									 
    num_iter = int( argv[2] )
    s = buildString( lsys, num_iter )
    print(s)


if __name__ == "__main__":
    main(sys.argv)

